appdocs101/urls.py
from django.conf.urls import patterns, url

from appdocs101 import views

urlpatterns = patterns('',
    url(r'^$', views.docs, name='docs'),

    url(r'^docs/$', views.docs, name='docs'),

    url(r'^register/$', views.register, name = 'register'),
    url(r'^signin/$', views.signin, name = 'signin'),
    url(r'^add_doc/$', views.add_doc, name = 'add_doc'),
    url(r'^add_doc2/$', views.add_doc2, name = 'add_doc2'),
    url(r'add_wishlist/$', views.add_wishlist, name = 'add_wishlist'),
    url(r'logout/$', views.logout, name = 'logout'),
    url(r'docs/$', views.docs, name = 'docs'),
    url(r'wishlists/$', views.wishlists, name = 'wishlists'),
    url(r'doc/(?P<doc_id>\d+)/$', views.doc, name = 'doc'),
    url(r'doc22/(?P<doc_id>\d+)/$', views.doc22, name = 'doc22'),
    url(r'wishlist/(?P<wishlist_id>\d+)/$', views.wishlist, name = 'wishlist'),
    url(r'add_comment/(?P<doc_id>\d+)/$', views.add_comment, name = 'add_comment'),
    url(r'accept_wishlist/$', views.accept_wishlist, name = 'accept_wishlist'),
    url(r'contributions/$', views.contributions, name = 'contributions'),

    #url(r'pedit_doc/(?P<doc_id>\d+)/$', views.pedit_doc, name = 'pedit_doc'),

    #url(r'pedit_doc/(?P<doc_id>\d+)/$', views.pedit_doc, name = 'pedit_doc'),
    
    url(r'^edit_doc2/(?P<doc_id>\d+)/$', views.edit_doc2, name = 'edit_doc2'),
    url(r'^revision/(?P<revision_id>\d+)/$', views.revision, name = 'revision'),
    url(r'^restore/(?P<revision_id>\d+)/$', views.restore, name = 'restore'),

    url(r'^pending_docs1/$', views.pending_docs1, name = 'pending_docs1'),
    url(r'^review_docs1/$', views.review_docs1, name = 'review_docs1'),


    url(r'^user/(?P<user_id>\d+)/$', views.user, name='user'),
)

appdocs101_web_app/urls.py
from django.conf.urls import patterns, include, url

#from appdocs101_web_app import views

from appdocs101 import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'appdocs101_web_app.views.home', name='home'),
    # url(r'^appdocs101_web_app/', include('appdocs101_web_app.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),

    #(r'^accounts/', include('userena.urls')),

    url(r'^appdocs101/', include('appdocs101.urls', namespace="appdocs101")), 

    url(r'^$', views.docs, name='docs'),

)  

appdocs101/models.py
from django.db import models
from datetime import datetime

from django.contrib.sessions.models import Session

# Create your models here.

""" Model to store user account details """
'''class User(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    password = models.CharField(max_length=200) # make sure to hash password before storing
    status = models.IntegerField(default=0) # 0 = 'ordinary user', 1 = 'admin'
    date_registered = models.DateTimeField('date registered')'''
  

""" Model to store software documentation details """
class Documentation(models.Model):
    title = models.TextField()
    software = models.CharField(max_length=200)
    version = models.CharField(max_length=200)
    operating_system = models.CharField(max_length=200)
    content = models.TextField()
    user = models.IntegerField()
    status = models.IntegerField(default=0) # 0 = 'unpublished', 1 = 'published'
    date_added = models.DateTimeField('date added')
    details = models.CharField(max_length=200, default = "version 1")
    collaborators_needed = models.BooleanField(default = False)

    def __unicode__(self):
	return self.title

""" Model to store software documentation wishlist/requests """
class Wishlist(models.Model):
    title = models.TextField()
    software = models.CharField(max_length=200)
    version = models.CharField(max_length=200)
    operating_system = models.CharField(max_length=200)
    content = models.TextField()
    user = models.IntegerField()
    status = models.IntegerField(default=0) # 0 = 'open', 1 = 'assigned/taken', 2 = 'granted' 
    date_added = models.DateTimeField('date added')

    def __unicode__(self):
	return self.title

    def accept(self, user):
	#transfer wishlist data to documentation
	doc = Documentation(title = self.title, software = self.software, 
	    version = self.version, operating_system = self.operating_system, 
	    user = user, status = 1, date_added = datetime.now())
	#wishlist = Wishlist.objects.filter(user = user)[0]
	#print wishlist.status

	#change wishlist status from open to taken
	self.status = 1
	self.save()

	#wishlist.status = 1
	#add to author list
	doc.authors_set.create(user = user, date_added = datetime.now())
 	wishlist.save()

	#print wishlist.status




""" Model to store software documentation comments """
'''class Documentation_Comments(models.Model):
    documentation = models.ForeignKey(Documentation)
    user = models.IntegerField()
    content = models.TextField()
    date_added = models.DateTimeField('date added')'''

""" Model to store software wishlist documentation comments """
class Wishlist_Comments(models.Model):
    wishlist = models.ForeignKey(Wishlist)
    user = models.IntegerField()
    content = models.TextField()
    date_added = models.DateTimeField('date added')

""" Model to store software documentation authors """
class Authors(models.Model):
    documentation = models.ForeignKey(Documentation)
    user = models.IntegerField()
    date_added = models.DateTimeField('date added')

    '''def __unicode__(self):
	return self.user'''

""" Model to store software documentation details """
class Documentation_Revisions(models.Model):
    documentation = models.ForeignKey(Documentation)
    title = models.TextField()
    software = models.CharField(max_length=200)
    version = models.CharField(max_length=200)
    operating_system = models.CharField(max_length=200)
    content = models.TextField()
    user = models.IntegerField()
    status = models.IntegerField() # 0 = 'unpublished', 1 = 'published'
    description = models.CharField(max_length=200)
    collaborators_needed = models.BooleanField(default = False)
    date_added = models.DateTimeField('date added')

    def __unicode__(self):
	return self.description

appdocs101/forms.py
from django import forms


class RegisterForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

class SigninForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())

class AddDocumentationForm(forms.Form):
    title = forms.CharField()
    software = forms.CharField()
    version = forms.CharField()
    operating_system = forms.CharField()
    status = forms.ChoiceField(widget = forms.Select(), choices = ([(0, 'Draft'), (1, 'Publish'), (2, 'Review')]))
    collaborators_needed = forms.BooleanField(widget = forms.CheckboxInput, required=False)


class AddWishlistForm(forms.Form):
    title = forms.CharField()
    software = forms.CharField()
    version = forms.CharField()
    operating_system = forms.CharField()
    content = forms.CharField(widget = forms.Textarea())

class CommentForm(forms.Form):
    content = forms.CharField(widget = forms.Textarea())

class ResourceForm(forms.Form):
    title = forms.CharField()
    link = forms.URLField()
    description = forms.CharField(widget = forms.Textarea())

appdocs101/views.py
# Create your views here.

from django.http import HttpResponse

from django.shortcuts import render
from django.contrib.auth.models import User

from django.contrib.auth import get_user_model #django user model

from appdocs101.forms import * #file where forms are located

from appdocs101.models import * #database

from django.contrib import messages #flash messages
from django.shortcuts import redirect

from django.http import HttpResponseRedirect

from django.contrib.auth import authenticate, login, logout

from datetime import datetime # date library

from django.shortcuts import get_object_or_404 #404 error if the data requested is not in the database

from django.core.urlresolvers import reverse

def user(request, user_id):
    return HttpResponse("You're looking at user %s" % user_id)

""" user registration """
def register(request):
    if request.method == 'POST': #if the form has been submitted
	form = RegisterForm(request.POST)
	if form.is_valid(): #form is validated
	    # add user to database

	    user = get_user_model().objects.create_user(form.cleaned_data['username'], form.cleaned_data['email'], form.cleaned_data['password'])

	    user.first_name = form.cleaned_data['first_name']
	    user.last_name = form.cleaned_data['last_name']
	    user.is_active = True
	    user.save()

	    messages.add_message(request, messages.INFO, "You have been successfully registered!!")
	    #render(request,  'appdocs101/signin.html')
	    return HttpResponseRedirect(reverse('africandesigns:signin'))

    else:
        form = RegisterForm()
    return render(request, 'appdocs101/register.html',  {'form': form, 'title': 'Register'})


""" user signin """
def signin(request):
    if request.method == 'POST':
	form = SigninForm(request.POST)
	if form.is_valid():
	    # check email and password match
	    query_user = get_user_model().objects.filter(email = form.cleaned_data['email'])
	    if len(query_user) == 1: 
		user = query_user[0]
		if user.check_password(form.cleaned_data['password']) == True: # authentication successful
		    if user.is_active: # account is active
		        messages.add_message(request, messages.INFO, "You have successfully signed in!")
		        #store user in session to indicate user is logged in
		        request.session['user'] = user
    		        return HttpResponseRedirect(reverse('appdocs101:add_doc'))
		    else: # account is inactive
	    	        messages.add_message(request, messages.INFO, "Sorry, you cannot login because you account has been deactivated!")		
	        else: # account is inactive
	            messages.add_message(request, messages.INFO, "Sorry, email address and/or password is incorrect!")

    else:
	form = SigninForm()
    return render(request, 'appdocs101/signin.html', {'form': form, 'title': 'Signin'})


""" Logout user """ 
def logout(request):
    #remove user from session to logout user if user is currently logged in
    if 'user' in request.session:
	del request.session['user']
	messages.add_message(request, messages.INFO, "You have successfully logged out!")
    #logout(request)
    #messages.add_message(request, messages.INFO, "You have successfully logged out!")
    #return render(request, 'appdocs101/logout.html')
    return HttpResponseRedirect(reverse('appdocs101:signin'))

""" adding software documentation/tutorial """
def add_doc(request):
    #check if form is submitted
    if request.method == 'POST':
        form = AddDocumentationForm(request.POST)
	#check if validation is successful
	if form.is_valid():
	    #add documentation details to database
	    doc = Documentation(title = form.cleaned_data['title'], software = form.cleaned_data['software'], version = form.cleaned_data['version'], operating_system = form.cleaned_data['operating_system'], content = request.POST['content'], user = request.session['user'].id, status = form.cleaned_data['status'], collaborators_needed = form.cleaned_data['collaborators_needed'], date_added = datetime.now())
	    doc.save()
	    messages.add_message(request, messages.INFO, "Your documentation was successfully added!")
	    #redirect to docs page      
	    HttpResponseRedirect(reverse('appdocs101:docs'))
    #form is not submitted, so display blank form
    else:
        form = AddDocumentationForm()
    return render(request, 'appdocs101/add_doc.html', {'form': form, 'title': 'Add Documentation'})


""" adding software documentation/tutorial """
def add_doc2(request):
    #check if form is submitted
    if request.method == 'POST':
        form = AddDocumentationForm(request.POST)
	#check if validation is successful
	if form.is_valid():
	    #add documentation details to database
	    doc = Documentation(title = form.cleaned_data['title'], software = form.cleaned_data['software'], version = form.cleaned_data['version'], operating_system = form.cleaned_data['operating_system'], content = request.POST['editor_content'], user = request.session['user'].id, status = form.cleaned_data['status'], collaborators_needed = form.cleaned_data['collaborators_needed'], date_added = datetime.now())
	    doc.save()
	    messages.add_message(request, messages.INFO, "Your documentation was successfully added!")
	    #redirect to docs page      
	    HttpResponseRedirect(reverse('appdocs101:docs'))
    #form is not submitted, so display blank form
    else:
        form = AddDocumentationForm()
    return render(request, 'appdocs101/add_doc2.html', {'form': form, 'title': 'Add Documentation'})

""" adding software wishlist documentation/tutorial """
def add_wishlist(request):
    #check if form is submitted
    if request.method == 'POST':
        form = AddWishlistForm(request.POST) 
	#check if validation is successful
	if form.is_valid():
	    #add documentation details to database
	    wishlist = Wishlist(title = form.cleaned_data['title'], software = form.cleaned_data['software'], version = form.cleaned_data['version'], operating_system = form.cleaned_data['operating_system'], content = form.cleaned_data['content'], user = request.session['user'].id, status = 0, date_added = datetime.now())
	    wishlist.save()
	    messages.add_message(request, messages.INFO, "Your wishist was successfully added.  You will be emailed when someone accepts your request!")
	    #redirect to wishlists page
	    HttpResponseRedirect(reverse('appdocs101:wishlists'))
    #form is not submitted, so display blank form
    else:
        form = AddWishlistForm()
    return render(request, 'appdocs101/add_wishlist.html', {'form': form, 'title': 'Add Wishlist'})

""" displaying list of documentations/tutorials """
def docs(request):
    #query to return all published documentations
    docs = Documentation.objects.filter(status = 1)
    return render(request, 'appdocs101/docs.html', {'title': 'Docs', 'docs': docs})

""" displaying wishlists of documentations users need a basic introduction/tutorial on """
def wishlists(request):
    #query to return all wishlists that have not yet been accepted
    wishlists = Wishlist.objects.filter(status = 0)
    return render(request, 'appdocs101/wishlists.html', {'title': 'Wishlist', 'wishlists': wishlists})

""" adding comments """
def add_comment(request, doc_id):
    #check if form is submitted
    if request.method == 'POST':
        form2 = CommentForm(request.POST)
	#check if validation is successful
	if form2.is_valid():

	    #query to return documentation with id "doc_id"
	    doc = Documentation.objects.get(id = doc_id)
	    #query to return author
	    user = get_user_model().objects.get(id = doc.user)

	    #add comment details to database
	    comment = doc.documentation_comments.create(user = user, content = form2.cleaned_data['content'], date_added = datetime.now())
	    comment.save()
	    messages.add_message(request, messages.INFO, "Your comment was successfully added!")
    #form is not submitted, so display blank form
    else:
        form2 = CommentForm()
    return render(request, 'appdocs101/add_comment.html', {'form': form2})


""" documentation/tutorial page """
def doc(request, doc_id): 
    #query to return documentation with id "doc_id", or raise Http404 error if data doesn't exist in database
    doc = get_object_or_404(Documentation,id = doc_id)
    #query to return author #Documentation.objects.get(id = doc_id)
    user = get_user_model().objects.get(id = doc.user)

    #get revision data
    revisions = doc.documentation_revisions_set.all()
    return render(request, 'appdocs101/doc.html', {'title': 'Docs', 'doc': doc, 'user': user, 'com':  add_comment(request, doc_id), 'revisions': revisions, })


""" documentation/tutorial page """
def doc22(request, doc_id): 
    #query to return documentation with id "doc_id", or raise Http404 error if data doesn't exist in database
    doc = get_object_or_404(Documentation,id = doc_id)
    #query to return author #Documentation.objects.get(id = doc_id)
    user = get_user_model().objects.get(id = doc.user)

    #get revision data
    revisions = doc.documentation_revisions_set.all()
    return render(request, 'appdocs101/doc22.html', {'title': 'Docs', 'doc': doc, 'user': user, 'com':  add_comment(request, doc_id), 'revisions': revisions, })

""" wishlist page """
def wishlist(request, wishlist_id):
    #query to return wishlist with id "wishlist_id"
    wishlist = Wishlist.objects.get(id = wishlist_id)
    #query to return user who added the wishlist
    user = get_user_model().objects.get(id = wishlist.user)
    return render(request, 'appdocs101/wishlist.html', {'title': 'Wishlist', 'wishlist': wishlist, 'user': user})


""" accept wishlist """
def accept_wishlist(request):
    if request.method == "POST":
        #query to return wishlist with id "wishlist_id"
        wishlist = Wishlist.objects.get(id = request.POST['wishlist_id'])
        doc = wishlist.accept(request.session['user'].id)
        messages.add_message(request, messages.INFO, "You accepted the wishlist!")
    return HttpResponseRedirect(reverse('appdocs101:add_doc'))

appdocs101/templates/appdocs101/add_comment.html
{% url 'add_comment' doc_id=doc.id as the_url %}
<form action = "{{ the_url }}" method = "post">
{% csrf_token %} 
<table>
{{ form.as_table }}
<tr>
<td>  <input type = "submit" name = "submit" value = "Submit">  </td>
</tr>
</table>

</form>

appdocs101/templates/appdocs101/add_doc.html
{% extends "appdocs101/base.html" %}
{% block content %}
<h1> Add Documentation </h1>
<form action = "/appdocs101/add_doc/" method = "post">
{% csrf_token %}
<table>
{{ form.as_table }}
<tr>
<td> <a href = "#"> Add author </a> </td>
</tr>
</table>

<textarea class = "content" name = "content" > </textarea>

 <input type = "submit" name = "submit" value = "Submit"> 


</form>








{% endblock %}

appdocs101/templates/appdocs101/add_doc2.html
{% extends "appdocs101/base.html" %}
{% block content %}
<h1> Add Documentation </h1>
<form action = "/appdocs101/add_doc2/" method = "post" onsubmit = "getContent()">
{% csrf_token %}
<table> 
{{ form.as_table }}
<tr>
<td> <a href = "#"> Add author </a> </td>
</tr>
</table>


	<input type = "button" value = "Add 1 column" onclick = "add_columns(1)">
	<input type = "button" value = "Add 2 columns" onclick = "add_columns(2)">
	<input type = "button" value = "Add 3 columns" onclick = "add_columns(3)">
	<input type = "button" value = "Add 4 columns" onclick = "add_columns(4)"> <br><br>


<div class="row-fluid">
	<div class="span2">
  	</div>

	<div class="span8">
	<div id = "span">




	</div>
	</div>
 
 
 

  	<div class="span2">
  	</div>


</div>


 <input type = "hidden" name = "editor_content" id = "editor_content" value = ""> 
 <input type = "submit" name = "submit" value = "Submit"> 


</form>



{% endblock %}

appdocs101/templates/appdocs101/add_wishlist.html
{% extends "appdocs101/base.html" %}
{% block content %}
<h1> Add Wishlist </h1>
<form action = "/appdocs101/add_wishlist/" method = "post">
{% csrf_token %}
<table>
{{ form.as_table }}
<tr>
<td> <input type = "submit" name = "submit" value = "Submit"> </td>
</tr>
</table>
</form>
{% endblock %} 

appdocs101/templates/appdocs101/base2.html
<html lang = "EN">
<meta charset = "utf-8">
<title> {{ title }} </title>
<head>

<style type="text/css">
textarea.content {
	height: 500px;
	}

</style>


{% load staticfiles %}

    <link href="{% static 'bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'docs.css' %}" rel="stylesheet">





              <!-- load the jQuery and require.js libraries -->
              <script type="text/javascript" src="http://cdn.aloha-editor.org/latest/lib/require.js"></script>
              <script type="text/javascript" src="http://cdn.aloha-editor.org/latest/lib/vendor/jquery-1.7.2.js"></script>
 
              <!-- load the Aloha Editor core and some plugins -->
              <script src="http://cdn.aloha-editor.org/latest/lib/aloha.js"
                                   data-aloha-plugins="common/ui,
                                                        common/format,
                                                        common/list,
                                                        common/link,
                                                        common/highlighteditables,
common/align,
common/characterpicker,
common/image,
common/table,
common/undo,
extra/toc">

              </script>
               
              <!-- load the Aloha Editor CSS styles -->
              <!-- <link href="http://cdn.aloha-editor.org/latest/css/aloha.css" rel="stylesheet" type="text/css" /> -->
 
              <!-- make all elements with class="editable" editable with Aloha Editor -->
              <script type="text/javascript">
                     Aloha.ready( function() {
                            var $ = Aloha.jQuery;
                            //$('.editable').aloha();
			    $('.editable').mahalo();
                     });
              </script>


</head>
<body>


<div class="container-fluid">

{% if messages %}
    {% for message in messages %}
	{{ message }}
    {% endfor %}
{% endif %}
<br>

{% if 'user' in request.session %}
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner"  >
    <ul class="nav">
    <li> <a href = "{% url 'appdocs101:add_doc' %}"> Add Documentation </a> </li> 
    <li> <a href = "{% url 'appdocs101:add_wishlist' %}"> Add Wishlist </a> </li> 
    <li> <a href = "{% url 'appdocs101:docs' %}"> View Documentations </a> </li> 
    <li> <a href = "{% url 'appdocs101:wishlists' %}"> View Wishlist </a> </li> 
    <li> <a href = "{% url 'appdocs101:contributions' %}"> My Contributions </a> </li> 
    <li> <a href = "{% url 'appdocs101:pending_docs1' %}"> Documentations in Progress </a> </li> 
    <li> <a href = "{% url 'appdocs101:review_docs1' %}"> Documentations Under Review </a> </li> 
    <li> <a href = "{% url 'appdocs101:logout' %}"> Logout </a>
{% else %}
    <li> <a href = "{% url 'appdocs101:signin' %}"> Signin </a> </li> 
    <li> <a href = "{% url 'appdocs101:register' %}"> Register </a> </li> 
{% endif %}
    </ul>
</div>
</div>

<!-- container-fluid  -->
</div> 

{% block content %}
{% endblock %}



</body>
</html>

appdocs101/templates/appdocs101/doc.html
{% extends "appdocs101/base.html" %}
{% block content %}


<div class="row-fluid">
  <div class="span9">


<h1> {{ doc.title }} </h1> 
{% load staticfiles %}
<a href = "{% url 'appdocs101:edit_doc2' doc_id=doc.id %}" title = "edit"> <img src = "{% static 'glyphicons_free/glyphicons/png/glyphicons_030_pencil.png'  %}" alt = "Isatou" width = "20" height = "20" /> </a> <br>

By: {{ user.username }} {{ user.first_name }} {{ user.last_name }} <br>

Software : {{ doc.software }} <br>
Version : {{ doc.version }} <br>
Operating System : {{ doc.operating_system }} <br>
<br>
{% autoescape off %} {{ doc.content }}{% endautoescape %} <br> <br>


  <!-- span9 -->
  </div> 
  <div class="span3">
<input type = "button" value = "Submit a relevant resource" />
<br> <br>
<b> Relevant Resources </b> <br>
<a href = "#"> How to use the AppDocs Word Editor </a> <br>
<a href = "#"> Adding other authors </a> <br> 

{% if revisions|length > 0 %}
    <b> Revisions </b> <br>
    {% for revision in revisions %}
        <a href = "{% url 'appdocs101:revision' revision_id=revision.id %}" title = "revision"> {{ revision.description }} </a> <br>
    {% endfor %}
{% endif %}
  <!-- span3 -->
  </div> 



<!-- row-fluid -->
</div> 


    
{% endblock %} 

appdocs101/templates/appdocs101/doc2.html
{% extends "appdocs101/base.html" %}
{% block content %}

<div class="container-fluid">
<div class="row-fluid">
  <div class="span9">


<h1> {{ doc.title }} </h1>
By: {{ user.username }} {{ user.first_name }} {{ user.last_name }} <br>

Software : {{ doc.software }} <br>
Version : {{ doc.version }} <br>
Operating System : {{ doc.operating_system }} <br>
<br>
{% autoescape off %} {{ doc.content }}{% endautoescape %} <br> <br>

<b> Was this useful? </b> <br>
<a href = "#"> Yes </a> <a href = "#"> No </a> <br>  <br>
95% found this useful! <br>

<input type = "button" value = "Leave a comment" />
<br> <br>
Leave a comment: <br>
<textarea cols = "100" rows = "10"> </textarea>



{% url 'add_comment' doc_id=doc.id as the_url2 %}

{{ the_url2 }}

{% include "appdocs101/add_comment.html" %}

{% autoescape off %} {{ com }} {% endautoescape %}


  <!-- span9 -->
  </div> 
  <div class="span3">
  <!-- span3 -->
<input type = "button" value = "Submit a relevant resource" />
<br> <br>
<b> Relevant Resources </b> <br>
<a href = "#"> How to use the AppDocs Word Editor </a> <br>
<a href = "#"> Adding other authors </a> <br>
  </div> 

<!-- row-fluid -->
</div> 
<!-- container-fluid  -->
</div> 

    
{% endblock %} 

appdocs101/templates/appdocs101/edit_doc.html
{% extends "appdocs101/base.html" %}
{% block content %}
<h1> Edit Documentation </h1>
<form action = "{% url 'appdocs101:edit_doc2' doc_id %}" method = "post">
{% csrf_token %}
<table>
{{ form.as_table }}
<tr>
<td> <a href = "#"> Add author </a> </td>
</tr>
</table>

<textarea class = "content" name = "content" > {{ content }} </textarea>

 <input type = "submit" name = "submit" value = "Save"> 


</form>
{% endblock %}

appdocs101/templates/appdocs101/register.html
{% extends "appdocs101/base.html" %}
{% block content %}
<h1> Register </h1>
<form action = "/appdocs101/register/" method = "post" >
{% csrf_token %}
<table>
{{ form.as_table }}
<tr>
<td> <input type = "submit" name = "submit" value = "Submit">  </td>
</tr>
</table>
</form>
{% endblock %}

appdocs101/templates/appdocs101/review_docs.html
{% extends "appdocs101/base.html" %}
{% block content %}
<h1> Documentations Under Review </h1>
{% if docs|length == 0 %}
    No documentation is currently being reviewed! <br>
{% else %}
    {% for doc in docs %}
	<a href = "{% url 'appdocs101:doc' doc_id=doc.id %}"> {{ doc.title }} </a> 
	{% if doc.collaborators_needed == True %}
	    (collaborators wanted)
	{% endif %}
        <hr>
    {% endfor %}
{% endif %}
{% endblock %} 

appdocs101/templates/appdocs101/revision.html
{% extends "appdocs101/base.html" %}
{% block content %}

<div class="container-fluid">
<div class="row-fluid">
  <div class="span9">

<b> Description: {{ revision.description }}

<a href = "{% url 'appdocs101:restore' revision_id=revision.id %}"> Restore this version </a> <hr>

<h1> {{ revision.title }} </h1> 


By: {{ user.username }} {{ user.first_name }} {{ user.last_name }} <br>

Software : {{ revision.software }} <br>
Version : {{ revision.version }} <br>
Operating System : {{ revision.operating_system }} <br>
<br>
{% autoescape off %} {{ revision.content }}{% endautoescape %} <br> <br>


  <!-- span9 -->
  </div> 
  <div class="span3">
  <!-- span3 -->
<input type = "button" value = "Submit a relevant resource" />
<br> <br>
<b> Relevant Resources </b> <br>
<a href = "#"> How to use the Apprevisions Word Editor </a> <br>
<a href = "#"> Adding other authors </a> <br> 


<!-- row-fluid -->
</div> 
<!-- container-fluid  -->
</div> 

    
{% endblock %} 

appdocs101/templates/appdocs101/wishlist.html
{% extends "appdocs101/base.html" %}
{% block content %}
<h1> {{ wishlist.title }} </h1>
Added_by : {{ user.username }} {{ user.first_name }} {{ user.last_name }} <br>
Software : {{ wishlist.software }} <br>
Version : {{ wishlist.version }} <br>
Operating System : {{ wishlist.operating_system }} <br>
<br>
{{ wishlist.content }} <br>

<form method = "post" action = "/appdocs101/accept_wishlist/">
{% csrf_token %}
<input type = "hidden" value = "{{ wishlist.id }}" name = "wishlist_id"  />
<input type = "submit" value = "Accept Request" />
</form>
    
{% endblock %} 

appdocs101/templates/appdocs101/wishlists.html
{% extends "appdocs101/base.html" %}
{% block content %}
<h1> Wishlist </h1>
{% if wishlists|length == 0 %}
    No wishlist has been added! <br>
{% else %}
    {% for wishlist in wishlists %}
	<a href = "{% url 'appdocs101:wishlist' wishlist_id=wishlist.id %}"> {{ wishlist.title }} </a> <hr>
    {% endfor %}
{% endif %}
    
{% endblock %} 